### PR TITLE
Split app into swappable components

### LINKED ISSUE #44: introduce components for future extensibility
An interesting framework for developing apps in Clojure is  `Components`.

It is about managing the lifecycle of the different components of an app. I think it would be good for us to develop our app using that pattern given that we already have the bases for it i.e. fake graph/network.

A downside of this approach is that `lein ring` doesnt work with this way of doing things as ring only allows using a single static handler and component is precisely about replacing/injecting those at runtime.

CC: @mehdisadeghi 

References:
- [conference video](https://www.youtube.com/watch?v=13cmHf_kt-Q)
- [compojure + component](https://github.com/metosin/compojure-api/wiki/Component-integration)
- [lein-ring problem](https://github.com/weavejester/lein-ring/issues/189)

### PR DESCRIPTION
**Pull request by carocad**
fixes #44 

@mehdisadeghi this is still in progress but the first sketch is already working. I encourage you to try it out and let me know your thoughts about it :)

Specially for this PR since it fundamentally changes the way that we interact with the server, how we reload and the control that we have over the configuration.

So the changes are:
- drop `lein ring` in favor of manual configuration
- creates a `main` function through which the app starts all components
- separate the different parts of the App into `components`. Please see #44 for more information
- allow to start, stop, reset the *complete* app through the REPL without restarting the process.
- rely on environment variables for configuration related vars. Based on [12 factor apps](https://12factor.net/). A special port number is still allowed in the terminal for compatibility with the way that we ran it with `lein ring`.
- compilation is now done through `lein uberjar` as opposed to `lein ring uberjar`

How does this change the way we develop the app?
- instead of using `lein ring server` for getting a server, now you start the repl (in cursive or through the terminal) and run `(reset)` in the `service.routing.dev` namespace. This cleans all previously allocated resources (graph, server, etc) and then starts a new one by reloading all changes in all files and restarting all components in the necessary order.
- running a server by itself is now `lein run`
- for configuring the app you would (as of now) need two special environment vars
  - `PORT` (required): the port that the server will bind to
  - `JOIN?`(optional, default: true) : whether or not the server should block the main thread (`true`) or not `false`.  

TODO: 
- figure out what is the best place to read the environment variables. I am still duplicating a bit of code for that
- add an `storage` component for reading the OSM file.

### CODE REVIEW

**Comment by mehdisadeghi** [comment]
Sounds good to me. There is a lot of ground to cover, it'll take me a while to go through it all.

**Comment by mehdisadeghi** [comment]
I suppose `PORT=3000 lein ring` should bring up the app? I get the following error: 

```
➜  pc-p561 service.routing git:(init) ✗ PORT=3000 lein run
Reflection warning, /tmp/form-init2724241515078507433.clj:1:1284 - call to static method invokeStaticMethod on clojure.lang.Reflector can't be resolved (argument types: unknown, java.lang.String, unknown).
2017-09-07 18:47:58.726:INFO::main: Logging initialized @2119ms
Reflection warning, ring/adapter/jetty.clj:44:3 - call to org.eclipse.jetty.server.ServerConnector ctor can't be resolved.
WARN clojure.tools.logging not found on classpath, compojure.api logging to console.
INFO :schema coercion enabled in compojure.api
INFO :spec coercion enabled in compojure.api
INFO :spec swagger generation enabled in compojure.api
Reflection warning, clojure/data/xml.clj:337:17 - call to method createXMLStreamReader can't be resolved (target class is unknown).
Reflection warning, service/routing/osm.clj:172:23 - reference to field close can't be resolved.
Reflection warning, service/routing/osm.clj:177:23 - reference to field close can't be resolved.
Welcome to the org.n7a235/service.routing App
Uncaught exception in thread main:
                          clojure.main.main       main.java:   37
                                        ...                      
                          clojure.main/main        main.clj:  386
                          clojure.main/main        main.clj:  423
                      clojure.main/null-opt        main.clj:  344
                    clojure.main/initialize        main.clj:  310
                      clojure.main/init-opt        main.clj:  279
                   clojure.main/load-script        main.clj:  277
                                        ...                      
                               user/eval814       REPL Input     
                                        ...                      
                 service.routing.core/-main        core.clj:   35
                 service.routing.core/-main        core.clj:   41
 com.stuartsierra.component.SystemMap/start  component.cljc:  178
    com.stuartsierra.component/start-system  component.cljc:  161
    com.stuartsierra.component/start-system  component.cljc:  163
                                        ...                      
   com.stuartsierra.component/update-system  component.cljc:  129
   com.stuartsierra.component/update-system  component.cljc:  135
                        clojure.core/reduce        core.clj: 6703
                                        ...                      
com.stuartsierra.component/update-system/fn  component.cljc:  139
      com.stuartsierra.component/try-action  component.cljc:  117
                         clojure.core/apply        core.clj:  659
                                        ...                      
   com.stuartsierra.component/eval1533/fn/G  component.cljc:    5 (repeats 2 times)
       service.routing.core.AppServer/start        core.clj:   15
               ring.adapter.jetty/run-jetty       jetty.clj:  147
           ring.adapter.jetty/create-server       jetty.clj:  109
          ring.adapter.jetty/http-connector       jetty.clj:   57
           java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
             clojure.lang.ExceptionInfo: Error in component :app in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start
     component: {:handler
                 {:path nil,
                  :method nil,
                  :info {:coercion :schema},
                  :childs
                  [{:path nil,
                    :method nil,
                    :info nil,
                    :childs
                    [{:path nil,
                      :method nil,
                      :info nil,
                      :childs
                      [{:path nil,
                        :method nil,
                        :info nil,
                        :childs nil,
                        :handler
                        #object[compojure.core$routes$fn__4018 0x2a5129f3 "compojure.core$routes$fn__4018@2a5129f3"]}
                       {:path "/swagger.json",
                        :method :get,
                        :info
                        {:no-doc true,
                         :name :compojure.api.swagger/swagger,
                         :public {:x-name :compojure.api.swagger/swagger}},
                        :childs nil,
                        :handler
                        #object[compojure.core$wrap_route_matches$fn__3999 0x6166d18b "compojure.core$wrap_route_matches$fn__3999@6166d18b"]}],
                      :handler
                      #object[compojure.core$routes$fn__4018 0x483381ea "compojure.core$routes$fn__4018@483381ea"]}
                     {:path "/spec/direction/:coordinates",
                      :method :get,
                      :info
                      {:coercion :spec,
                       :public
                       {:summary "direction with clojure.spec",
                        :parameters
                        {:path
                         {Keyword Any,
                          :coordinates :service.routing.spec/raw-coordinates},
                         :query
                         {Keyword Any,
                          {:k :steps}
                          #object[clojure.core$boolean_QMARK_ 0x3e6f3f28 "clojure.core$boolean_QMARK_@3e6f3f28"],
                          {:k :radiuses} :service.routing.spec/raw-radiuses,
                          {:k :alternatives}
                          #object[clojure.core$boolean_QMARK_ 0x3e6f3f28 "clojure.core$boolean_QMARK_@3e6f3f28"],
                          {:k :language}
                          #object[clojure.core$string_QMARK___4952 0x40317ba2 "clojure.core$string_QMARK___4952@40317ba2"]}},
                        :responses
                        {200
                         {:schema :service.routing.spec/direction, :description ""}}}},
                      :childs nil,
                      :handler
                      #object[compojure.core$wrap_routes$fn__4117 0x122c8b64 "compojure.core$wrap_routes$fn__4117@122c8b64"]}],
                    :handler
                    #object[compojure.core$routes$fn__4018 0x6fc9f8bc "compojure.core$routes$fn__4018@6fc9f8bc"]}],
                  :handler
                  #object[compojure.api.middleware$wrap_inject_data$fn__13717 0x36d476c2 "compojure.api.middleware$wrap_inject_data$fn__13717@36d476c2"]},
                 :options {:port "3000", :join? true}}
      function: #'com.stuartsierra.component/start
        reason: :com.stuartsierra.component/component-function-threw-exception
        system: {:config-options {:port "3000", :join? true},
                 :app
                 {:handler
                  {:path nil,
                   :method nil,
                   :info {:coercion :schema},
                   :childs
                   [{:path nil,
                     :method nil,
                     :info nil,
                     :childs
                     [{:path nil,
                       :method nil,
                       :info nil,
                       :childs
                       [{:path nil,
                         :method nil,
                         :info nil,
                         :childs nil,
                         :handler
                         #object[compojure.core$routes$fn__4018 0x2a5129f3 "compojure.core$routes$fn__4018@2a5129f3"]}
                        {:path "/swagger.json",
                         :method :get,
                         :info
                         {:no-doc true,
                          :name :compojure.api.swagger/swagger,
                          :public {:x-name :compojure.api.swagger/swagger}},
                         :childs nil,
                         :handler
                         #object[compojure.core$wrap_route_matches$fn__3999 0x6166d18b "compojure.core$wrap_route_matches$fn__3999@6166d18b"]}],
                       :handler
                       #object[compojure.core$routes$fn__4018 0x483381ea "compojure.core$routes$fn__4018@483381ea"]}
                      {:path "/spec/direction/:coordinates",
                       :method :get,
                       :info
                       {:coercion :spec,
                        :public
                        {:summary "direction with clojure.spec",
                         :parameters
                         {:path
                          {Keyword Any,
                           :coordinates :service.routing.spec/raw-coordinates},
                          :query
                          {Keyword Any,
                           {:k :steps}
                           #object[clojure.core$boolean_QMARK_ 0x3e6f3f28 "clojure.core$boolean_QMARK_@3e6f3f28"],
                           {:k :radiuses} :service.routing.spec/raw-radiuses,
                           {:k :alternatives}
                           #object[clojure.core$boolean_QMARK_ 0x3e6f3f28 "clojure.core$boolean_QMARK_@3e6f3f28"],
                           {:k :language}
                           #object[clojure.core$string_QMARK___4952 0x40317ba2 "clojure.core$string_QMARK___4952@40317ba2"]}},
                         :responses
                         {200
                          {:schema :service.routing.spec/direction,
                           :description ""}}}},
                       :childs nil,
                       :handler
                       #object[compojure.core$wrap_routes$fn__4117 0x122c8b64 "compojure.core$wrap_routes$fn__4117@122c8b64"]}],
                     :handler
                     #object[compojure.core$routes$fn__4018 0x6fc9f8bc "compojure.core$routes$fn__4018@6fc9f8bc"]}],
                   :handler
                   #object[compojure.api.middleware$wrap_inject_data$fn__13717 0x36d476c2 "compojure.api.middleware$wrap_inject_data$fn__13717@36d476c2"]},
                  :options {:port "3000", :join? true}}}
    system-key: :app
clojure.lang.Compiler$CompilerException: clojure.lang.ExceptionInfo: Error in component :app in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key :app, :component #service.routing.core.AppServer{:handler #Route{:info {:coercion :schema}, :childs [#Route{:childs [#Route{:childs [#Route{} #Route{:path "/swagger.json", :method :get, :info {:no-doc true, :name :compojure.api.swagger/swagger, :public {:x-name :compojure.api.swagger/swagger}}}]} #Route{:path "/spec/direction/:coordinates", :method :get, :info {:coercion :spec, :public {:summary "direction with clojure.spec", :parameters {:path {Keyword Any, :coordinates :service.routing.spec/raw-coordinates}, :query {Keyword Any, #schema.core.OptionalKey{:k :steps} #object[clojure.core$boolean_QMARK_ 0x3e6f3f28 "clojure.core$boolean_QMARK_@3e6f3f28"], #schema.core.OptionalKey{:k :radiuses} :service.routing.spec/raw-radiuses, #schema.core.OptionalKey{:k :alternatives} #object[clojure.core$boolean_QMARK_ 0x3e6f3f28 "clojure.core$boolean_QMARK_@3e6f3f28"], #schema.core.OptionalKey{:k :language} #object[clojure.core$string_QMARK___4952 0x40317ba2 "clojure.core$string_QMARK___4952@40317ba2"]}}, :responses {200 {:schema :service.routing.spec/direction, :description ""}}}}}]}]}, :options {:port "3000", :join? true}}, :system #<SystemMap>}, compiling:(/tmp/form-init2724241515078507433.clj:1:73)
PORT=3000: command not found```

**Comment by mehdisadeghi** [comment]
I think we should consider a default port while running the app, is there any reason not to do so?

**Comment by carocad** [comment]
@mehdisadeghi yeah, I havent implemented it yet :D

as for the exception it looks like a bug to me. I guess I messed up at some point. I will check that tomorrow

**Pull request merged**
